# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  bucket:
    type: string
    description: Target GCS bucket for snapshots/backups (3–63 chars, lowercase letters, digits, hyphens).
  storage-class:
    type: string
    description: Optional GCS storage class (STANDARD|NEARLINE|COLDLINE|ARCHIVE).
    default: STANDARD
  path:
    type: string
    description: Optional object prefix (<=1024 bytes, no NULL bytes).
    default: ""
  validate-credentials:
    type: boolean
    description: Optional online validation of the service account JSON by obtaining an OAuth token (WhoAmI).
    default: false
  credentials:
    type: secret
    description: |
      A Juju Secret URI (a format of secret:xxxx) with a GCP service-account JSON key:
      1. secret-key: The secret key corresponding to the GCP IAM service account JSON key.
